<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="D:/PROJ/Contoso_Data_Fabric/ContosoFabric.Fabric/ContosoFabric.Fabric.csproj" /></ItemGroup></Project>
