from __future__ import annotations

import json
import uuid
from pathlib import Path

from .planner import build_plan
from .scenarios import SCENARIOS
from .spec import ProjectSpec


def _stable_id(project: str, item: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"contoso-fabric:{project}:{item}"))


def _platform(project: str, item_type: str, display_name: str, description: str = "") -> dict:
    return {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": item_type, "displayName": display_name, "description": description},
        "config": {"version": "2.0", "logicalId": _stable_id(project, display_name)},
    }


def _cell(source: str, *, parameters: bool = False) -> dict:
    metadata = {"microsoft": {"language": "python", "language_group": "synapse_pyspark"}}
    if parameters:
        metadata["tags"] = ["parameters"]
    return {"cell_type": "code", "execution_count": None, "id": str(uuid.uuid4()), "metadata": metadata, "outputs": [], "source": [line + "\n" for line in source.rstrip().splitlines()]}


def _notebook(cells: list[dict]) -> dict:
    return {"cells": cells, "metadata": {"kernelspec": {"display_name": "Synapse PySpark", "language": "Python", "name": "synapse_pyspark"}, "language_info": {"name": "python"}}, "nbformat": 4, "nbformat_minor": 5}


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _lakehouse(root: Path, spec: ProjectSpec, name: str) -> None:
    item = root / "fabric" / f"{name}.Lakehouse"
    item.mkdir(parents=True, exist_ok=True)
    _write_json(item / ".platform", _platform(spec.project.name, "Lakehouse", name, "Generated by Contoso Fabric Builder"))
    _write_json(item / "lakehouse.metadata.json", {})
    _write_json(item / "shortcuts.metadata.json", {"shortcuts": []})


def _notebook_item(root: Path, spec: ProjectSpec, name: str, cells: list[dict]) -> None:
    item = root / "fabric" / f"{name}.Notebook"
    item.mkdir(parents=True, exist_ok=True)
    _write_json(item / ".platform", _platform(spec.project.name, "Notebook", name, "Generated by Contoso Fabric Builder"))
    _write_json(item / "notebook-content.ipynb", _notebook(cells))


def _parameters(spec: ProjectSpec) -> str:
    ws = spec.fabric.workspace.name or "YOUR_WORKSPACE"
    return f'''# Parameters - safe to change after deployment
workspace_name = {ws!r}
bronze_lakehouse = {spec.fabric.bronze_lakehouse!r}
silver_lakehouse = {spec.fabric.silver_lakehouse!r}
gold_lakehouse = {spec.fabric.gold_lakehouse!r}
landing_format = {spec.landing.format!r}
'''


def _bronze_code(spec: ProjectSpec) -> str:
    tables = list(SCENARIOS[spec.business.scenario].tables)
    return f'''from pyspark.sql import functions as F

tables = {tables!r}
raw_root = f"abfss://{{workspace_name}}@onelake.dfs.fabric.microsoft.com/{{bronze_lakehouse}}.Lakehouse/Files/raw"
table_root = f"abfss://{{workspace_name}}@onelake.dfs.fabric.microsoft.com/{{bronze_lakehouse}}.Lakehouse/Tables"

for table in tables:
    if landing_format == "parquet":
        df = spark.read.parquet(f"{{raw_root}}/{{table}}.parquet")
    elif landing_format == "csv":
        df = spark.read.option("header", True).option("inferSchema", True).csv(f"{{raw_root}}/{{table}}.csv")
    elif landing_format == "delta":
        df = spark.read.format("delta").load(f"{{raw_root}}/{{table}}")
    else:
        raise ValueError(f"Unsupported landing format: {{landing_format}}")
    df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").save(f"{{table_root}}/{{table}}")
    print(f"bronze {{table}}: {{df.count()}} rows")
'''


def _silver_code() -> str:
    return '''bronze_root = f"abfss://{workspace_name}@onelake.dfs.fabric.microsoft.com/{bronze_lakehouse}.Lakehouse/Tables"
silver_root = f"abfss://{workspace_name}@onelake.dfs.fabric.microsoft.com/{silver_lakehouse}.Lakehouse/Tables"

entities = {
    "customer": ("dim_customer", ["CustomerKey"]),
    "store": ("dim_store", ["StoreKey"]),
    "product": ("dim_product", ["ProductKey"]),
    "date": ("dim_date", ["Date"]),
    "currencyexchange": ("dim_currencyexchange", ["Date", "FromCurrency", "ToCurrency"]),
    "sales": ("fact_sales", ["OrderKey", "LineNumber"]),
    "orders": ("fact_orders", ["OrderKey"]),
    "orderrows": ("fact_order_rows", ["OrderKey", "LineNumber"]),
}

for source, (target, keys) in entities.items():
    df = spark.read.format("delta").load(f"{bronze_root}/{source}")
    existing_keys = [k for k in keys if k in df.columns]
    if existing_keys:
        df = df.dropDuplicates(existing_keys)
    df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").save(f"{silver_root}/{target}")
    print(f"silver {target}: {df.count()} rows")
'''


def _gold_code() -> str:
    return '''from pyspark.sql import functions as F

silver_root = f"abfss://{workspace_name}@onelake.dfs.fabric.microsoft.com/{silver_lakehouse}.Lakehouse/Tables"
gold_root = f"abfss://{workspace_name}@onelake.dfs.fabric.microsoft.com/{gold_lakehouse}.Lakehouse/Tables"

sales = spark.read.format("delta").load(f"{silver_root}/fact_sales")

gold_sales = (
    sales
    .withColumn("OrderDay", F.to_date("OrderDate"))
    .withColumn("NetRevenue", F.col("Quantity") * F.col("NetPrice"))
    .withColumn("Cost", F.col("Quantity") * F.col("UnitCost"))
    .withColumn("GrossMargin", F.col("NetRevenue") - F.col("Cost"))
    .groupBy("OrderDay", "CurrencyCode")
    .agg(F.sum("NetRevenue").alias("NetRevenue"), F.sum("GrossMargin").alias("GrossMargin"), F.sum("Quantity").alias("Units"), F.countDistinct("OrderKey").alias("Orders"), F.countDistinct("CustomerKey").alias("Customers"))
)

gold_sales.write.format("delta").mode("overwrite").option("overwriteSchema", "true").save(f"{gold_root}/sales_daily")
print(f"gold sales_daily: {gold_sales.count()} rows")
'''


def compile_bundle(spec: ProjectSpec, output_dir: str | Path, stop_after: str | None = None) -> dict:
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    plan = build_plan(spec, stop_after)
    _write_json(out / "plan.json", plan)
    _write_json(out / "truth_manifest.json", {"status": "generated-contract", "generator": "sql-bi-contoso-v2", "effectiveSeed": 0, "expectedTables": list(SCENARIOS[spec.business.scenario].tables), "ordersRequested": plan["generation"]["ordersCount"], "note": "Row counts and KPIs are populated after local generation/reconciliation in a later V1 increment."})

    stages = plan["stages"]
    if "bronze" in stages:
        _lakehouse(out, spec, spec.fabric.bronze_lakehouse)
        _notebook_item(out, spec, "Bronze_Load", [_cell(_parameters(spec), parameters=True), _cell(_bronze_code(spec))])
    if "silver" in stages:
        _lakehouse(out, spec, spec.fabric.silver_lakehouse)
        _notebook_item(out, spec, "Silver_Transform", [_cell(_parameters(spec), parameters=True), _cell(_silver_code())])
    if "gold" in stages:
        _lakehouse(out, spec, spec.fabric.gold_lakehouse)
        _notebook_item(out, spec, "Gold_Build", [_cell(_parameters(spec), parameters=True), _cell(_gold_code())])
    return plan
