using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Azure.Core;
using Azure.Identity;
using ContosoFabric.Fabric.Definitions;

namespace ContosoFabric.Fabric.Api;

public sealed class FabricDefinitionDeployer
{
    private static readonly Uri ApiRoot = new("https://api.fabric.microsoft.com/v1/");
    private static readonly string[] FabricScopes = ["https://api.fabric.microsoft.com/.default"];
    private static readonly HttpClient Http = new() { BaseAddress = ApiRoot, Timeout = Timeout.InfiniteTimeSpan };
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly FabricRestClient _catalog;
    private readonly TokenCredential _credential;

    public FabricDefinitionDeployer(FabricRestClient catalog, TokenCredential? credential = null)
    {
        _catalog = catalog;
        _credential = credential ?? new AzureCliCredential();
    }

    public Task<FabricItemInfo> EnsureSemanticModelAsync(
        string workspaceId,
        string displayName,
        FabricItemDefinition definition,
        IProgress<string>? progress = null,
        CancellationToken cancellationToken = default)
        => EnsureDefinitionItemAsync(
            workspaceId,
            "SemanticModel",
            "semanticModels",
            displayName,
            definition,
            progress,
            cancellationToken);

    public Task<FabricItemInfo> EnsureReportAsync(
        string workspaceId,
        string displayName,
        FabricItemDefinition definition,
        IProgress<string>? progress = null,
        CancellationToken cancellationToken = default)
        => EnsureDefinitionItemAsync(
            workspaceId,
            "Report",
            "reports",
            displayName,
            definition,
            progress,
            cancellationToken);

    private async Task<FabricItemInfo> EnsureDefinitionItemAsync(
        string workspaceId,
        string itemType,
        string endpoint,
        string displayName,
        FabricItemDefinition definition,
        IProgress<string>? progress,
        CancellationToken cancellationToken)
    {
        definition.Validate();
        if (string.IsNullOrWhiteSpace(displayName))
            throw new ArgumentException($"{itemType} display name is required.", nameof(displayName));

        var encodedDefinition = new
        {
            format = definition.Format,
            parts = definition.Parts.Select(part => new
            {
                path = part.Path,
                payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(part.Content)),
                payloadType = "InlineBase64"
            }).ToArray()
        };

        var existing = (await _catalog.ListItemsAsync(workspaceId, itemType, cancellationToken))
            .Where(item => item.DisplayName.Equals(displayName, StringComparison.OrdinalIgnoreCase))
            .ToArray();

        if (existing.Length > 1)
            throw new InvalidOperationException($"More than one {itemType} is named '{displayName}'. Rename duplicates before using idempotent deployment.");

        if (existing.Length == 1)
        {
            progress?.Report($"Updating {itemType}: {displayName}");
            using var update = await SendAsync(
                HttpMethod.Post,
                $"workspaces/{workspaceId}/{endpoint}/{existing[0].Id}/updateDefinition",
                new { definition = encodedDefinition },
                cancellationToken);
            await WaitForOperationIfNeededAsync(update, cancellationToken);
            return existing[0];
        }

        progress?.Report($"Creating {itemType}: {displayName}");
        using var create = await SendAsync(
            HttpMethod.Post,
            $"workspaces/{workspaceId}/{endpoint}",
            new
            {
                displayName,
                description = "Generated by Contoso Fabric Builder",
                definition = encodedDefinition
            },
            cancellationToken);
        await WaitForOperationIfNeededAsync(create, cancellationToken);

        for (var attempt = 0; attempt < 12; attempt++)
        {
            var created = (await _catalog.ListItemsAsync(workspaceId, itemType, cancellationToken))
                .FirstOrDefault(item => item.DisplayName.Equals(displayName, StringComparison.OrdinalIgnoreCase));
            if (created is not null)
                return created;
            await Task.Delay(TimeSpan.FromSeconds(2), cancellationToken);
        }

        throw new InvalidOperationException($"Fabric accepted {itemType} '{displayName}' but it was not visible in the item catalog after creation.");
    }

    private async Task WaitForOperationIfNeededAsync(HttpResponseMessage initial, CancellationToken cancellationToken)
    {
        if (initial.StatusCode != HttpStatusCode.Accepted)
            return;

        var operationId = GetHeader(initial, "x-ms-operation-id") ?? GetHeader(initial, "operation-id");
        if (string.IsNullOrWhiteSpace(operationId))
            throw new InvalidOperationException("Fabric returned 202 Accepted without an operation ID.");

        var deadline = DateTimeOffset.UtcNow.AddMinutes(30);
        var delay = GetRetryAfter(initial, 5);
        while (DateTimeOffset.UtcNow < deadline)
        {
            if (delay > TimeSpan.Zero)
                await Task.Delay(delay, cancellationToken);

            using var state = await SendAsync(HttpMethod.Get, $"operations/{operationId}", null, cancellationToken);
            using var document = await ReadDocumentAsync(state, cancellationToken);
            var status = document.RootElement.TryGetProperty("status", out var statusElement)
                ? statusElement.GetString() ?? "Unknown"
                : "Unknown";

            if (status.Equals("Succeeded", StringComparison.OrdinalIgnoreCase))
                return;
            if (status.Equals("Failed", StringComparison.OrdinalIgnoreCase))
            {
                var error = document.RootElement.TryGetProperty("error", out var errorElement)
                    ? errorElement.ToString()
                    : "Unknown Fabric operation error";
                throw new InvalidOperationException($"Fabric definition deployment failed: {error}");
            }

            delay = GetRetryAfter(state, 5);
        }

        throw new TimeoutException($"Fabric operation {operationId} did not finish within 30 minutes.");
    }

    private async Task<HttpResponseMessage> SendAsync(HttpMethod method, string url, object? body, CancellationToken cancellationToken)
    {
        var requestUri = new Uri(ApiRoot, url);
        var serialized = body is null ? null : JsonSerializer.Serialize(body, JsonOptions);

        for (var attempt = 1; attempt <= 6; attempt++)
        {
            var token = await _credential.GetTokenAsync(new TokenRequestContext(FabricScopes), cancellationToken);
            using var request = new HttpRequestMessage(method, requestUri);
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token.Token);
            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            if (serialized is not null)
                request.Content = new StringContent(serialized, Encoding.UTF8, "application/json");

            var response = await Http.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
            if (response.StatusCode == HttpStatusCode.TooManyRequests && attempt < 6)
            {
                var retry = GetRetryAfter(response, Math.Min(30, attempt * 2));
                response.Dispose();
                await Task.Delay(retry, cancellationToken);
                continue;
            }

            if (response.IsSuccessStatusCode)
                return response;

            var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
            var status = (int)response.StatusCode;
            response.Dispose();
            throw new FabricApiException(status, $"Fabric API {method} {requestUri} failed with HTTP {status}. {responseBody}", responseBody);
        }

        throw new InvalidOperationException("Fabric definition API retry policy exhausted.");
    }

    private static string? GetHeader(HttpResponseMessage response, string name)
        => response.Headers.TryGetValues(name, out var values) ? values.FirstOrDefault() : null;

    private static TimeSpan GetRetryAfter(HttpResponseMessage response, int fallbackSeconds)
    {
        if (response.Headers.RetryAfter?.Delta is TimeSpan delta)
            return delta;
        if (response.Headers.RetryAfter?.Date is DateTimeOffset date)
            return date > DateTimeOffset.UtcNow ? date - DateTimeOffset.UtcNow : TimeSpan.Zero;
        return TimeSpan.FromSeconds(fallbackSeconds);
    }

    private static async Task<JsonDocument> ReadDocumentAsync(HttpResponseMessage response, CancellationToken cancellationToken)
    {
        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        return await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken);
    }
}
